---
- name: fix sql IP in php-fpm
  hosts: all
  tasks:
    - name: replace sql IP in php conf file
      shell: sed 's/host.*/host\' => \'DB_IP\'/g\'  /var/www/my_drupal/web/sites/default/settings.php | grep host
    - name: restart php-fpm
      service:
        name: php-fpm 
        state: restarted

 