

# [START cloudbuild_basic_config]
steps:

  # Entrypoint, timeout and environment variables
  - id: 'get-gcve-creds-pc1'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'pc-1'
    timeout: 5m
    entrypoint: bash
    args: 
    - '-c'
    - |
        ./set_credentials.sh

  - id: 'pc-1 tf apply'
    name: 'hashicorp/terraform:latest'
    dir: 'pc-1'
    entrypoint: 'sh'
    args: 
    - '-c'
    - |
        cp /workspace/gcve-pc1.credentials.auto.tfvars .
        terraform init || exit 1
        terraform plan || exit 1
options:
  pool:
    name: projects/537433851712/locations/us-central1/workerPools/gcve-worker
# [END cloudbuild_basic_config]

