

# [START cloudbuild_basic_config]
steps:

  # Entrypoint, timeout and environment variables
  - id: 'get-gcve-creds-pc1'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'pc-1'
    timeout: 5m
    entrypoint: bash
    args: 
    - '-c'
    - |
        ./set_credentials.sh ${_PC1_NAME} ${_PC1_LOCATION} $PROJECT_ID
        cp ./${_PC1_NAME}-create_vms.sh /tfvarsvolume/${_PC1_NAME}-create_vms.sh
    volumes:
    - name: 'tfvarsvolume'
      path: '/tfvarsvolume'

  - id: 'build vms'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    timeout: '3200s'
    dir: 'pc-1'
    entrypoint: 'sh'
    args: 
    - '-c'
    - |
        curl -L -o - "https://github.com/vmware/govmomi/releases/latest/download/govc_$(uname -s)_$(uname -m).tar.gz" | tar -C /usr/local/bin -xvzf - govc
        ls  
        govc version
        cp /tfvarsvolume/${_PC1_NAME}-create_vms.sh ./${_PC1_NAME}-create_vms.sh
        ./${_PC1_NAME}-create_vms.sh
    volumes:
    - name: 'tfvarsvolume'
      path: '/tfvarsvolume'
options:
  pool:
    name: projects/$PROJECT_NUMBER/locations/us-central1/workerPools/gcve-pool
  logging: CLOUD_LOGGING_ONLY
# [END cloudbuild_basic_config]

